
data_path: /home/charlie/Desktop/MJCFConvert/mjcf2o3d/unimals_100 #/network/scratch/c/charlie.gauthier/unimals_100
batch_size: 32
num_workers: 4
grid_size: 32
fewer_files: 10 # -1 # files[:fewer_files]
splits: [0.8,0.2] #train-/test/-/train/  # either 2-tuple or 3-tuple that sums to 1, or "train-test", which uses train/test split from the dataset

data_aug:
  patch_shuf: False
  hybridize: False
  mutate: False
  masked_autoencoder: False