
data_path: /home/charlie/Desktop/MJCFConvert/mjcf2o3d/unimals_100/ # /network/scratch/c/charlie.gauthier/voxvae/unimals_100
batch_size: 32
num_workers: 4
grid_size: 32
fewer_files: 10 # -1 # files[:fewer_files]
splits: [0.8, 0.2]  # either 2-tuple or 3-tuple that sums to 1, or "traintest", which uses train/test split from the dataset